import Head from 'next/head'
import Grid from '@mui/material/Grid';
import Card from '@mui/material/Card';
import CardHeader from '@mui/material/CardHeader';
import Avatar from '@mui/material/Avatar';

import { useRouter } from 'next/router';

import axios from 'axios';

import Layout from '../components/Layout';

export default function Home({ categories }) {

  const router = useRouter()

  return (
    <>
      <Head>
        <title>Django-NextJs App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <Grid container style={{ marginTop: '75px', paddingLeft: '5px', paddingRight: '5px' }} spacing={3}>
          {categories.map(category => (
            <Grid item xs={12} md={4} >
              <Card onClick={() => router.push(`/categories/${category.slug}`)} style={{ cursor: 'pointer' }}>
                <CardHeader 
                  avatar = {
                    <Avatar aria-label='category'>
                      C
                    </Avatar>
                  }
                  title={`${category.name}`}
                  subheader={`See all ${category.name} business`}
                />              
              </Card>
            </Grid>
          ))}
        </Grid>
      </Layout>
      
    </>
  )
}

export async function getServerSideProps() {
  // Fetch our Data
  const { data } = await axios.get("http://127.0.0.1:8000/categories/")

  return {
    props: {
      categories: data.results
    }
  }
}
